# Base image
FROM python:3.9

# Define a working directory
WORKDIR /app

# Copiar o requirements.txt para o container
COPY requirements.txt .

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Instalar o Jupyter Notebook
RUN pip install jupyter

# Expor a porta 8888 para acessar o Jupyter Notebook
EXPOSE 8888

# Comando para iniciar o Jupyter Notebook quando o container for iniciado
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
